### PR TITLE
Issue 46

### PR DESCRIPTION
**Pull request by badgersow**
Hey there!
Please review my changes.
Thank you very much.

### CODE REVIEW

**Comment by Grundlefleck** [comment]
Hey @badgersow,

This looks like a great effort. I like the names of classes you've used, and the test coverage is great.

I have a few issues though, which means I can't merge right away:

- by default, this approach will always load classes to get the line numbers. This can cause errors when running from the CLI, and the classes are not available from the classpath, or they fail to load, etc. There are two options: A) convert the existing code (LineNumbers), in it's current form, to not load classes. B) only call LineNumbers when creating the error for a unit test, and only do it for unit tests, where the class is likely to be loaded anyway. I much prefer option A, and the good news is, if LineNumbers can get the information via reflection, then it can get it via bytecode too. I'll describe this in more detail in a moment.
- I don't mind copying in code if the license permits, but if it's copied in, I don't think we can't strip the original copyright, according to the Redistribution section [here](http://www.apache.org/licenses/LICENSE-2.0). Of course, IANAL, so please correct if wrong. Let's see if the previous issue makes it a moot point or not.

It's very close though!

So, reflection. I'm going by the principle that in order for reflection to work at all, the bytecode must contain all the information necessary -- I don't see how it could possibly work otherwise. I *think* that the reflection classes (`Class`, `Method`, `Field`) used in LineNumbers are only used as a convenience. 

For example, `getDeclaringClass` is called, but it's only needed to check that an instance of `LineNumbers` contains the same class as that which the `Member` belongs to when `getLineNumber` is called. We can either enforce this further up the call stack, or throw an exception later when we don't find the member, because this can only be a programmer error on our part, not the users. For example, in `LineNumbersUtil`, we take a fieldName string, and if you trace back all the code paths that end up invoking that method, the field name comes from ASM. So as long as we're careful, we can ensure all callers only pass a valid class and field name combination. That way we don't need an instance of `Class` to call `getDeclaredField` on, and we don't need to do `Class.forName` in `LineNumbersUtil`.

Later uses of the `Member` type are to construct a key, for later lookup in a map, and that seems to be it. Actual storing of that key against a line number is done with "vanilla" ASM code that doesn't need to load classes. The key for the field is simple, it's just the name. The key for the method is a bit more tricky, for example it calls ASM's `Type.getMethodDescriptor(Method)`, but there's another method on that class that does the equivalent, but takes a `Type` instead, which doesn't require reflection. It's possible to supply an equivalent instance of `Type`, in fact we could probably pass it all the way from the visitor that raised the error. For example, where we detect setter methods, it's in the setter method itself, so the method descriptor can't be that far away. Constructor is the trickiest, but I believe it's doable (not sure how off the top of my head though).

Once we don't need to do `Class.forName`, the ASM visitor that retrieves line numbers can reuse the code within Mutability Detector that attempts various ways of visiting classes and adds some custom error handling (check out the class `InformationRetrievalRunner`).

To conclude, the bad news is I can't accept the PR as it is, but the good news is all the structure is there and looking good, and I see no reason the implementation can't be tweaked to avoid loading classes.

Are you happy to pursue the changes I've described?

**Comment by badgersow** [comment]
Hi.

Thank you for your comment. I am really didn't think about the problem of loading classes.
You are completely correct: there is no need to load classes when we can avoid it.
Thanks again for your suggestion about the way code can be changed.
I really like the format of working with MutabilityDetector: I am learning a lot from every issue and comment.
I will proceed with fixing the problem in the next few days.

About the licensing issue: Let's discuss this after code will be accepted by you.
Thanks again, I'll continue my work.

**Comment by badgersow** [comment]
Hi, @Grundlefleck !

Could you please advice about possible better way to implement the problem I ran into?

First, I rewrote `LineNumbers` class not to use `Class.forName` and it works OK, you was completely right about this.

Now I try to use common analysis functionality (`InformationRetrievalRunner`) for line numbers info (see class `LineNumbersInformation`).
As before, I want `CodeLocation` class to be able to print itself via `prettyPrint` method with line numbers info.
But now I can't simply use `LineNumbersUtil` in `CodeLocation.prettyPrint`, I need to obtain `LineNumbersInformation` from `AnalysisDatabase`.
I investigated how analysis information is processed now: it is obtained in `MutabilityCheckerFactory` and passed as parameter to some checkers.
The only difference is this: old analysis information (`PrivateMethodInvocationInformation`, etc.) was required only for some checkers, but line numbers info will be required for ALL checkers (it is necessary for `CodeLocation` to print itself).

As one of the possible ways I can do the following:

* Create `CodeLocationFactory` with line numbers info and pass it to all checkers in `MutabilityCheckersFactory`. You can see I do it for `ArrayFieldMutabilityChecker` and `CollectionWithMutableElementTypeToFieldChecker` in latest commit. This will allow for all checkers to create `CodeLocation` instances via `CodeLoca
tionFactory` and that `CodeLocation` instances will be aware about line numbers.

* Rewrite all checkers and tests to create `CodeLocation` instances only via `CodeLocationFactory`.

But before I refactor checkers and tests I want to ask you, what do you think about this approach? 
Maybe I overcomplicate things and you know how it can be solved easier?

Thanks very much for your time!

**Comment by Grundlefleck** [comment]
Hi Efim,

Sounds like you're definitely making progress in the right direction, good
stuff.

I haven't looked at the diffs, but the way you suggested sounds fine, but
just to complicate things, let me throw a few other thoughts into the mix:

- did you intend to keep CodeLocation as an immutable value type? I would
like that, and wasn't sure if you were proposing that CodeLocation could
call LineNumbersInformation or if the checkers would do that and just pass
source file and line number to a CodeLocation constructor.

- I wonder if perhaps the checker superclass that is inherited by all could
help keep track of line numbers as the class was being analysed. Meaning,
if the superclass had a lineNumber() and sourceFile() method that returned
the right value when calling addReason(), it would save having to have a
LineNumbersInformation class at all. At the expense of having a more
complicated super class, and probably having some way of making sure a
subclass didn't accidentally break the methods. This would save on
complexity of looking up the location separately, which can be complicated
if trying to specify completely unambiguous parts of the class to look up.
It would also imply there would be only one pass over the bytecode, which
would be a little bonus. I've not thought through exactly how this would
work, do you think it's worth trying? Since it's all implementation detail
we can do as you are proposing now and revisit later.

If you don't want to consider these points just now, and continue with your
suggested approach, I am fine with that too. I like that the parts being
worked on are internal, gives a lot of freedom to just get it working and
change later if we feel the need.

Is that helpful?

**Comment by badgersow** [comment]
Thanks for reply!

Your observations are helpful, 
I'll consider them during my investigation.

**Pull request closed without merging**
