### PR TITLE
adding Gitter info to txt files

### PR DESCRIPTION
**Pull request by VestigeJ**
Hey Graham,

I'm still here and getting better acquainted with Git, finally figured it out and I'm trying to work on Issue #72 - I can't find the html file to add/edit Gitter onto their as well though.

### CODE REVIEW

**Comment by Grundlefleck** [comment]
Merged what you had so far, looked good to me. Which HTML were you referring to, what you land on by going to mutabilitydetector.org?

**Comment by VestigeJ** [comment]
Yes! The GitHub hosted page said that its usually dropped into the src but I couldn't locate it.

**Comment by Grundlefleck** [comment]
I think it comes from the branch gh-pages. I don't know off the top of my head how you could have possibly discovered that. I think using the gh-pages branch is a GitHub convention, and I happen to point to a processed version of that that from the domain name registrar for MutabilityDetector.org. Can't remember the details of all that though, hasn't changed in 3 years, so I may be misremembering.

**Comment by VestigeJ** [comment]
Thanks for the info Graham,
I found the branches and by the time I looked at it you already added the Gitter info there. :)
I restored the branch a few minutes ago to change some spelling and layout on the Gitter Badge.

**Comment by Grundlefleck** [comment]
Ah, cool. I edited the Wiki pages using the GitHub UI. I don't actually know which repository the wiki pages exist in.

Also, I had expected that the gh-pages branch, hosting the page at mutabilitydetector.org, would need to be changed, but there's already a link to the contact page, and I think that's good enough.

Lemme know if you have other corrections you want to make, but for now, I'm happy. Many thanks!

**Pull request merged**
