### PR TITLE
#51 - Error message improved for unwrapped Collections

### PR DESCRIPTION
**Pull request by kwahsog**
Hi,

First time commit: resolving issue #51 by changing the displayed error message to "Field is not a wrapped collection type."

Thanks.

### CODE REVIEW

**Comment by Grundlefleck** [comment]
Great! I will look at the contents of the PR in a day or two (New Year
holidays and all). Thanks!

**Comment by kwahsog** [comment]
Ok, thanks. Happy NY!

**Comment by Grundlefleck** [comment]
Hey @kwahsog thanks so much for taking the time to grab an issue.

I feel like this error message could be improved even more. I'm thinking along the lines of a message that's more specific. Meaning, a field must be wrapped and copied, so there are several combinations of errors that can be made (no copying or wrapping; no wrapping; no copying) and the message could indicate which ones are the problem. 

If I write up an issue describing the behaviour I think would be useful, would you be interested in implementing it?

**Comment by kwahsog** [comment]
Hi,

Thanks for the merge. I am keen to contribute further, so it'd be great if you could write up the issue and I'll get working on it.

On a side note: I was trying to fix [https://github.com/MutabilityDetector/MutabilityDetector/issues/43](issue 43), but couldn't work out where the first message was being generated to edit it.

**Pull request merged**
