### PR TITLE
Added TimingUtil to make the SessionResultsFormatter's seconds taken …

### PR DESCRIPTION
**Pull request by civild**
…testable (issue #92)

The test class for SessionResultsFormatter can now verify that the seconds taken will be correct.
I'm not sure if adding a setter for TimingUtil is the best approach to inject the mock - let me know what you think.

### CODE REVIEW

**Comment by Grundlefleck** [comment]
Hey @civild. The approach looks good, in that it allows you to manipulate the time to make a deterministic test, good stuff. I do have a couple of specific nitpicks though :)

-  I don't see a need to add the setter. Why not make a constructor parameter? There's only a couple of places the constructor is called, and they can all be changed quite easily. The benefit is that you can then make the `timingUtil` field `final`. `SessionResultsFormatter` is annotated as `@Immutable`, and a setter breaks that.
- The TimingUtil class is marked `@Immutable` but isn't (I can explain why, but it might be fun for you to use Mutability Detector itself to find out why). Not that absolutely everything needs to be immutable, just that if it's annotated as `@Immutable`, it should be.

However, I am happy to merge as-is. If you would like to address these two points, then great! if not, I thank you for your contribution, it is gratefully received :)

**Comment by civild** [comment]
I actually started with passing it in the constructor and thought it may be best not to change the constructor of the class, but it makes sense to do so to avoid having the setter and to be able to make the field final.

Also, good shout on actually using MutabilityDetector to check my new class is _actually_ immutable... 😄 

```
joe$ java -jar MutabilityDetector-0.10.0-SNAPSHOT.jar -cp . -m '.*TimingUtil' -v
classes.org.mutabilitydetector.misc.TimingUtil is NOT_IMMUTABLE
	Can be subclassed, therefore parameters declared to be this type could be mutable subclasses at runtime. [Class: org.mutabilitydetector.misc.TimingUtil]
	Field can have an abstract type (java.time.Clock) assigned to it. [Field: jvmStartTimeClock, Class: org.mutabilitydetector.misc.TimingUtil]
	Field can have an abstract type (java.time.Clock) assigned to it. [Field: currentTimeClock, Class: org.mutabilitydetector.misc.TimingUtil]
```

I guess the two around java.time.Clock could be addressed by using a concrete type instead of the abstract one, but since we need the class to be non-final so that Mockito can mock it I guess it's better to remove the Immutable annotation instead.

**Comment by Stephan202** [comment]
> \[..\] but since we need the class to be non-final so that Mockito can mock it \[..\]

Note that [as of Mockito 2.1](https://github.com/mockito/mockito/wiki/What's-new-in-Mockito-2#unmockable) there is opt-in support for mocking `final` classes. We've used this feature in a large project for several months now, and it works well.

**Comment by civild** [comment]
@Stephan202 hadn't realised that, thanks! I'll issue a separate pull request to upgrade to the latest version of Mockito so that we can make the class final (just in case there's any potential issues).

**Pull request merged**
