### PR TITLE
Support List.of et al as creating immutable collections #169

### PR DESCRIPTION
**Pull request by fma1**
- Added AbstractImmutableCollection and AbstractImmutableMap to JdkConfiguration for Java 9+ List.of(), Set.of() and Map.of()
- Added tests for Java 9 List, Set and Map

One thing I was not sure about is the catch block I added to JdkConfiguration. I added a println statement but then deleted it. Normally an empty catch block is a code smell but in this case we do not want to propagate the exception, and normally in production code, a logger is used but I did not really see one being used here.

### CODE REVIEW

**Comment by Grundlefleck** [comment]
Hello @fma1 and thanks for the PR.

This doesn't quite match the needs of the issue. Here's an example test case that demonstrates the problem:


```
public class UsesJava9ImmutableCollectionsTest {
    @Test public void canUseListOfImmutably() {
        assertInstancesOf(UsesListOf.class, areImmutable());
    }

    public static final class UsesListOf {
        private final List<String> things;

        public UsesListOf(String... things) {
            this.things = List.of(things);
        }
    }
}
```
This class is fine, it is immutable, but fails with:
```
org.mutabilitydetector.unittesting.MutabilityAssertionError: 
Expected: org.mutabilitydetector.benchmarks.mutabletofield.UsesJava9ImmutableCollectionsTest$UsesListOf to be IMMUTABLE
     but: org.mutabilitydetector.benchmarks.mutabletofield.UsesJava9ImmutableCollectionsTest$UsesListOf is actually NOT_IMMUTABLE
    Reasons:
        Field is not a wrapped collection type. You can use this expression: Collections.unmodifiableList(new ArrayList<String>(things)) [Field: things at org.mutabilitydetector.benchmarks.mutabletofield.UsesJava9ImmutableCollectionsTest$UsesListOf(UsesJava9ImmutableCollectionsTest$UsesListOf.java:1)]
    Allowed reasons:
        None.
```
So part of why the checked exception stands out a little bit, is that you need to catch it because you are trying to reference internal classes by name. What I think would be better suited here, is to have a definition that's used somewhere in the area of `CollectionTypeWrappedInUnmodifiableIdiomChecker`. That's the bit of code that allows `this.myList = Collections.unmodifiableList(new ArrayList<>(sourceList));` and it does but having an allow-list of methods that are known to produce immutable collections. So in contrast, there is no hardcoding of `java.util.Collections$UnmodifiableList`, but instead there's hardcoding of the methods used.

They could still be configured in `JdkConfiguration`, although now that I look at it,  I'm reminded that `CollectionTypeWrappedInUnmodifiableIdiomChecker` has this config, so it's probably just as good a place.

There may need to be some changes in that class, I actually can't remember if it only supports "copy+wrap" together, or if it would also support them separately, allowing e.g. `List.of` and `List.copyOf` without an intermediate collection to copy into.

Let me know if you need further clarification.

**Comment by fma1** [comment]
Hi @Grundlefleck ,

So I added another map to `CollectionTypeWrappedInUnmodifiableCheckerIdiom`:

```
        public final ImmutableMap<String, String> FIELD_TYPE_TO_IMMUTABLE_METHOD = ImmutableMap.<String, String>builder()
                .put("java.util.Set", "of")
                .put("java.util.List", "of")
                .put("java.util.Map", "of")
                .build();
```

And I looked at the class and it seems there's a `wrapInUnmodifiableMethod()` that checks against the map and that's called by `checkWrappedInUnmodifiable()`. I do understand what you are saying about checking against the method itself. One of the things I am wondering at this point is if this is the correct place to add the Java 9 immutable factory methods. I am wondering that because it seems like this class is specifically for the wrapped unmodifiable idiom, which is different from the Java 9 factory methods.

I think I would probably have to look more deeper, because it seems that `CollectionTypeWrappedInUnmodifiableIdiomChecker` is used here:
```
                    UnmodifiableWrapResult unmodifiableWrapResult = new CollectionTypeWrappedInUnmodifiableIdiomChecker(
                            fieldInsnNode, typeAssignedToField, mutableTypeInfo.hardcodedCopyMethods(), fieldSignature)
                            .checkWrappedInUnmodifiable();
```

I looked through some other classes in the codebase, and it seems like there is checking of copying first, because obviously if you modify the mutable backing list, you modify the view itself.

**Comment by Grundlefleck** [comment]
@fma1 

I think you're on the right track. There are two choices I see:

- add another class similar to `CollectionTypeWrappedInUnmodifiableIdiomChecker` that checks and allows for List.of, etc.
- modify `CollectionTypeWrappedInUnmodifiableIdiomChecker` to encompass both the wrapping-unmodifiable idiom, as well as assigning List.of etc, without a copy.

Both approaches seem totally valid to me. There's no requirement to keep these classes exactly as they are now. I have a mild preference for the latter, but I feel confident you'd be able to make a good choice, so I'll leave it to you. Feel free to seek advice prior if you want.

Really happy to see your continued attempts. I aim to be better at responding sooner.

**Comment by fma1** [comment]
Sorry I was using `git filter-branch`. I'm going to refork the repository.

**Comment by Grundlefleck** [comment]
Great work @fma1 !

**Pull request closed without merging**
