### PR TITLE
Fix for issue 111

### PR DESCRIPTION
**Pull request by sband**

### CODE REVIEW

**Comment by sband** [comment]
Need to fix the maven jar signing issue

**Comment by Grundlefleck** [comment]
Hey @sband I'm not quite following the commits here. It looks from the java change you have a minimal fix for #111 but it's closed with a reference to maven jar signing? Is there anything I can do to help?

**Comment by sband** [comment]
Yeah, the travis build is failing for my checkin with the below error, i am not sure how this error appeared that is why i closed the pull request. Will re-open after fixing this. I can reproduce this issue on my local.

[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ MutabilityDetector ---
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2018-03-06T06:20:53+05:30
[INFO] Final Memory: 35M/372M

**Comment by sband** [comment]
oh, then can i re-open this pull request ?

**Comment by sband** [comment]
Thanks for the feedback @Grundlefleck. I will accommodate this one and update the pull request. Until then please keep it open.

**Comment by sband** [comment]
Hey @Grundlefleck  i have implemented the changes you recommended, i.e 
1. Included the FrameNode check in recursion
2. Added a test case for this check
I haven't included the benchmarks for this as i haven't been able to understand the concept of benchmark, what are benchmarks, why do we need them ? when do we write benchmarks ?

**Comment by sband** [comment]
Hey @Grundlefleck 
i have added some improvements to my previous check-in. I noticed that my previous was covering only one part of the ternary operator branch as well as the branches of if-else statement. 
Now these changes cover both branches and then fails fast if found mutable. 
I have also added benchmark classes to cover the possible cases that i could think of. 
Please have a look at the changes and merge this one.

Thanks 
Sanket (sband)

**Comment by Grundlefleck** [comment]
@sband looks good, merging. Thanks very much.

Glad you added the test cases directly, I think it's better to have the coverage closer to the class, and when I added the test case to ClientOfMutabilityDetector, I didn't yet know what class it was that caused the problem. Good choice of test cases.

**Pull request merged**
